name: Ejecutar Pruebas

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/action-python@v5
      with:
        python-version: "3.10"
        
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        
    - name: Ejecutar pytest
      run: |
        pytest
